language: python
python:
  - "3.8"
  - "3.10"
dist: focal
cache: pip

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/28fee1f221c705851580
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always

before_install:
  - curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.1/install.sh | bash
  - curl -sSL https://install.python-poetry.org | python -
  - source $HOME/.nvm/nvm.sh
  - nvm install 16
  - nvm use 16

install:
  - poetry install
  - npm install -g mountebank --production

before_script:
  - mkdir -p $HOME/$DEST
  - curl -u $KEY $HOST/$FILE > $HOME/$DEST/$FILE
  - mb &

script:
  - poetry run pytest --cov -m 'logic or mbtest'

after_success:
  - poetry run codecov
