language: python
python:
  - "3.8"
  - "3.10"
dist: focal
cache: pip

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/28fee1f221c705851580
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always


env:
  - SET="-m 'logic or live or destructive or remote or mbtest'"

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install nodejs
  - sudo apt-get install npm
  - curl -sSL https://install.python-poetry.org | python -

install:
  - poetry install
  - npm install -g mountebank --production

before_script:
  - mkdir -p $HOME/$DEST
  - curl -u $KEY $HOST/$FILE > $HOME/$DEST/$FILE
  - mb &

script:
  - coverage run setup.py test --addopts "$SET"

after_success:
  - codecov
